{
  "file_data": [
    {
      "desc": {
        "cause": "Under Investigation",
        "cluster": false,
        "cust_a": {
          "masked": true,
          "val": 4
        },
        "etr": "2020-11-19T13:00:00-0400",
        "start": "2020-11-18T15:13:00-0400"
      },
      "geom": {
        "p": [
          "}~`qGf_o|J"
        ]
      },
      "id": "1",
      "title": "Outage Information"
    }
  ],
  "file_title": "030322"
}
