{
  "file_data": [
    {
      "desc": {
        "cause": "Under Investigation",
        "cluster": false,
        "cust_a": {
          "val": 11
        },
        "etr": "2020-12-05T22:30:00-0400",
        "start": "2020-12-05T18:34:59-0400"
      },
      "geom": {
        "p": [
          "y|oqGd|okK"
        ]
      },
      "id": "2",
      "title": "Outage Information"
    }
  ],
  "file_title": "030322"
}
