{
  "file_data": [
    {
      "desc": {
        "cause": "Under Investigation",
        "cluster": false,
        "cust_a": {
          "val": 10
        },
        "etr": "2020-12-08T21:15:00-0400",
        "start": "2020-12-08T17:18:00-0400"
      },
      "geom": {
        "p": [
          "g}unGbdpgK"
        ]
      },
      "id": "4",
      "title": "Outage Information"
    }
  ],
  "file_title": "030322"
}
