{
  "file_data": [
    {
      "desc": {
        "cause": "Under Investigation",
        "cluster": false,
        "cust_a": {
          "masked": true,
          "val": 4
        },
        "etr": "2020-12-11T17:45:00-0400",
        "start": "2020-12-11T13:23:15-0400"
      },
      "geom": {
        "p": [
          "alwoGt}{_K"
        ]
      },
      "id": "1",
      "title": "Outage Information"
    }
  ],
  "file_title": "030322"
}
