{
  "file_data": [
    {
      "desc": {
        "cause": "Under Investigation",
        "cluster": false,
        "cust_a": {
          "masked": true,
          "val": 4
        },
        "etr": "2020-12-13T02:00:00-0400",
        "start": "2020-12-12T19:07:00-0400"
      },
      "geom": {
        "p": [
          "u|poGpcncK"
        ]
      },
      "id": "1",
      "title": "Outage Information"
    }
  ],
  "file_title": "030322"
}
