{
  "file_data": [
    {
      "desc": {
        "cause": "Under Investigation",
        "cluster": false,
        "cust_a": {
          "val": 5
        },
        "etr": "2020-11-30T22:30:00-0400",
        "start": "2020-11-30T18:58:50-0400"
      },
      "geom": {
        "p": [
          "myooG|i`dK"
        ]
      },
      "id": "1",
      "title": "Outage Information"
    }
  ],
  "file_title": "030322"
}
