{
  "file_data": [
    {
      "desc": {
        "cause": "Under Investigation",
        "cluster": false,
        "cust_a": {
          "val": 772
        },
        "etr": "2020-12-15T12:00:00-0400",
        "start": "2020-12-15T07:12:11-0400"
      },
      "geom": {
        "a": [
          "_wygGbsooK{lCzW{uSuz@pfA}oCl}B{tErOpAlR~Cti@~Lvq@z`@f|MdqI"
        ],
        "p": [
          "e_hhGrgkoK"
        ]
      },
      "id": "3",
      "title": "Outage Information"
    }
  ],
  "file_title": "030322"
}
