{
  "file_data": [
    {
      "desc": {
        "cause": "Under Investigation",
        "cluster": false,
        "cust_a": {
          "masked": true,
          "val": 4
        },
        "etr": "2020-12-23T00:15:00-0400",
        "start": "2020-12-22T19:33:00-0400"
      },
      "geom": {
        "p": [
          "yf~lG`sjhK"
        ]
      },
      "id": "2",
      "title": "Outage Information"
    }
  ],
  "file_title": "030322"
}
