{
  "file_data": [
    {
      "desc": {
        "cause": "Under Investigation",
        "cluster": false,
        "cust_a": {
          "val": 9
        },
        "etr": "2020-11-18T11:30:00-0400",
        "start": "2020-11-18T08:04:38-0400"
      },
      "geom": {
        "p": [
          "cvxoGh|ybK"
        ]
      },
      "id": "1",
      "title": "Outage Information"
    }
  ],
  "file_title": "030322"
}
