{
  "file_data": [
    {
      "desc": {
        "cause": "Under Investigation",
        "cluster": false,
        "cust_a": {
          "masked": true,
          "val": 4
        },
        "etr": "2020-12-16T20:45:00-0400",
        "start": "2020-12-16T16:22:00-0400"
      },
      "geom": {
        "p": [
          "cv{oG~go_K"
        ]
      },
      "id": "8",
      "title": "Outage Information"
    }
  ],
  "file_title": "030322"
}
